spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    stream:
      function:
        definition: paymentEventConsumer
      bindings:
        paymentEventConsumer-in-0:
          destination: payment-event

server:
  port: 8081
